### ISSUE TITLE
Messy Uniform & Vest Gear

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#111]
A lot of our uniform and vest gear has changed over time and thus some historical weird stuff snuck in over time such as one tourniquet being in the uniform and the other in the vest.

With issue #107 and #95 coming up in the next version I think it's a good time to properly order items again in the uniform.

I propose the following order I also employed for my vietnam faction:

- 4x Bandage (Basic)
- 6x Basic Field Dressing (QuikClot)
- 2x Tourniquet (CAT)
- 1x Morphine
- 1x Epinephrene
- Rest of the uniform items (differs per role)

This will require the updating contributors to completely remove all uniform items except the basic bandage and the quikclots and then refill them in the correct order.

**Comment by JamesTheClarke** [comment]
Implemented for [Russian Army draft v.1.14.2](/CntoDev/compositions/tree/Russian-Standard-Faction-Update-v1.14.2)

**Comment by JamesTheClarke** [comment]
Implemented for [US Army v.1.14.2](/CntoDev/compositions/tree/US-Army-Standard-Faction-Update-v1.14.2)

**Comment by JamesTheClarke** [comment]
Reopened due to still being present in TFN and PMC.

**Comment by Seb105** [comment]
I have created the following spreadsheet:
https://docs.google.com/spreadsheets/d/1crRSUNR6M-DZmp6Nd8Y8uORxtGAIdU7ZWsgE2q6W9KI/edit?usp=drive_web&ouid=100502761207613371838

It automatically generates a script that allows you to regenerate the entire faction from scratch, based on items you input. I think this would make faction maintainence a lot easier, it works already however:

- I haven't actually filled out each loadout (Laziness)
- DAGR, FALCON, NIGHTBIRD need to be renamed to the role description shown. This is because the quote marks in the role description in-game break the script.

At some point, I'd like to see faction updates done using this spreadsheet as it is so much less error-prone.

**Comment by JamesTheClarke** [comment]
Maybe we should postpone this issue and #84 to v1.14.4 in order to quickly deploy the fixes made in PR #137 to MMT.

Especially the pilot and co-pilot fixes in #137 are highly requested and working on #111 and #84 might delay that a bit further.

what do you think @baegel49 and @milivojm ?

**Comment by milivojm** [comment]
Sounds good.

**Comment by baegel49** [comment]
Fine by me

**Comment by JamesTheClarke** [comment]
Updated both issues to v1.14.4. Please review and merge PR #137 .

Afterward, I'll compile the zip file and create the git release.

**Comment by JamesTheClarke** [comment]
I think this issue was closed because of a misunderstanding. #111 and #84 are both still open and relevant - I just reassigned them from milestone v1.14.3 to v1.14.4 to deal with them for that release.

#111 still needs to be completed for TFN, it is complete for US and RU standard factions.
