### ISSUE TITLE
PLT HQ missing in TFN faction

### ISSUE THREAD

**Issue by milivojm** [CntoDev/compositions#130]
There is no PLT HQ in TFN faction composition.

**Comment by milivojm** [comment]
Hmm, there is platoon but it's placed in separate folder for unknown reasons.

**Comment by JamesTheClarke** [comment]
I've noticed this bug too during my Vietnam Campaign as the factions were based on the Standard factions. Personally, I suspect this to be a result of our Arma Additions update because the bug only appeared after we updated all the factions.

Atm it doesn't really harm much, only places the PLT section at the bottom of the slotting screen. But definitely, something to be looked at and fixed.

**Comment by milivojm** [comment]
This is Arma 3 bug. I retried reordering, in the mission itself looks fine. Saved it into compositions. Opened new mission, drag and drop from compositions and bingo, Task Force Noctem layer is created out of nowhere. Then, I wanted to 'cheat the system', created Task Force Noctem layer, moved all TFN items into that layer, saved it as composition. Opened new mission, drag and drop and now two Task Force Noctem layers appear. 

After that, restarted the game without any mods. Tried to create any composition of multiple groups from vanilla units. Saved as compositions and in new mission game by default creates one layer named as composition while moving other groups into proper place. Can't do much about this.

**Comment by milivojm** [comment]
Opened a bug

[https://feedback.bistudio.com/T155906](https://feedback.bistudio.com/T155906)
[https://discord.com/channels/105462288051380224/108187245529268224/793471273959292968](https://discord.com/channels/105462288051380224/108187245529268224/793471273959292968)

**Comment by milivojm** [comment]
Bug has been fixed on dev branch.

**Comment by milivojm** [comment]
Bohemia fixed this bug in dev-branch/2.202

https://feedback.bistudio.com/T155906#2144038
