### ISSUE TITLE
Distribute compositions on Steam Workshop?

### ISSUE THREAD

**Issue by freghar** [CntoDev/compositions#131]
We could upload our (at least reference) compositions to Steam Workshop upon release, allowing MMs (and anybody else) to just subscribe to them, and get automatic updates to them (via Steam client, which auto-downloads updates to subscribed items, even if Arma 3 Launcher is not used).

> Players can now share custom compositions from the game directly to the Steam Workshop. They can do so by accessing Arma 3’s extensive library of weapons, vehicles, equipment, characters, structures, and props available and arranging their in-game assets in the editor. When they’re done, all they need to do is save their selected assets as a custom composition and click on the appropriate icon to publish it to the Steam Workshop. Compositions can include anything from full-blown military camps to specific roadblocks or checkpoints, a Halloween pumpkin festival, a simple table and chairs, or anything in between. 

https://arma3.com/news/arma-3-update-200

**Comment by JamesTheClarke** [comment]
I agree, this could speed up the distribution process and lower the chance for manual errors. The old auto-download bat file hasn't worked since Mikoi's infrastructure was removed so currently MMs only have the latest version if they download it manually.

I haven't fiddled around with this feature yet, is it a lot of work to set up and maintain or fairly straight forward?

**Comment by baegel49** [comment]
I'm a fan, though this would have to be done through an "official" CNTO account IMO

**Comment by JamesTheClarke** [comment]
To participate in the Steam Workshop the account has to own the game. Our CNTO account does fulfill that requirement, however it is impractical to use it for the distribution because we'd have to change the password every time either an SSgt or the Mission Making Manager changes, this happens usually several times a year. There are underlying applications that all also need to be updated whenever the PW changes so this would increase manual workload and error potential quite a bit.

A simpler solution is to how we admin the Steam group: make individual accounts admins and moderators so the roles (and their upload rights) can be changed without raising password security concerns and related increased workload. From my understanding, this is how the vast majority of modding teams work on Steam already: they don't create new accounts but instead just add and remove individual members to the dev team depending on their needs.

**Comment by JamesTheClarke** [comment]
I've just created a use case with the BI wiki instructions: https://community.bistudio.com/wiki/Eden_Editor:_Custom_Composition

It's published on Steam (visible only to friends): https://steamcommunity.com/sharedfiles/filedetails/?id=2403148296

We can add and remove contributors just like with any other mod published on Steam.

**Comment by JamesTheClarke** [comment]
I did another test because I was worried that if an SSgt publishes a composition from the CNTO Steam Account that it would shut down the game server (since technically it's logged in simultaneously).

However, luckily I was able to play the game locally and publish a composition via Steam Workshop as CNTO without crashing our game server: https://steamcommunity.com/sharedfiles/filedetails/?id=2421788811

So in that regard publication via CNTO Main Account is totally doable.

@baegel49 @Shiny-CNTO @Shadisica you guys good with using that method for the upcoming v2.0.0 comp update?

**Comment by Shadisica** [comment]
Yes, very much in favor of distributing the factions through Steam Workshop.
I think they should be fully public, to avoid having the NEED to be friends with the CNTO account and keeping Mission Making accessible to all members. The compostions are useless to anyone not running our modpack anyway.

**Comment by JamesTheClarke** [comment]
Yeah I agree, just wanted to present the two options as they are available to us and see if I'm alone with the opinion to make it fully public. ;)

**Comment by Shiny-CNTO** [comment]
I am good with having it fully open honestly. I love the idea and glad you tested if it would crash the server :)

**Comment by baegel49** [comment]
agreed with making it fully public.

**Comment by JamesTheClarke** [comment]
@baegel49 @Shadisica @Shiny-CNTO new quirk of the Workshop I just discovered when trying to set up the Steam release of v2.0.0: if the Steam account in question never bought anything you can only publish items to "friends-only".

Since our main account was gifted its copy I'll have to buy a cheap DLC to enable the share public option.

**Comment by Shiny-CNTO** [comment]
What the fuck. Stupid rule but yeah go for it.

**Comment by Shadisica** [comment]
Yeah, absolutely go for it.

**Comment by JamesTheClarke** [comment]
@Shiny-CNTO @Shadisica @baegel49 so I bought the charity DLC and the good news is the CNTO account can now post on the discussion forums, meaning I can stop using my personal Steam account to advertise the community which will lower my inbox spam. The bad news is it's still not enough to publish items on the workshop. I did some further digging and apparently you need to 1.) have bought something and 2.) have at least 5 dollars in your steam wallet.

I'm going to add 5 dollars now from the community funds to the CNTO wallet. If it doesn't work I'll refund the amount.

**Comment by JamesTheClarke** [comment]
Took quite a bit of work but I have published all essential compositions via Steam Workshop: https://steamcommunity.com/sharedfiles/filedetails/?id=2421823024

Each entry in the collection features a description of the module and some promotional material in case a random Arma freak stumbles upon them.
