### ISSUE TITLE
All TFN camo modules are broken

### ISSUE THREAD

**Issue by Seb105** [CntoDev/compositions#145]
They do not contain an "execute code (3den)" module at all.

**Comment by JamesTheClarke** [comment]
Can you expound what exactly is broken? When I place down the current uniform, helmet and vest camo modules it changes them for TFN without any problems.

**Comment by Seb105** [comment]
My current camo modules were last modified 23/01/2021, the date that these files were commited to the repo so yes. Ay you sure you are running the latest version?

When you place down a module, nothing happens to TFN. The vehicles module is placed, but nothing happens to TFN itself. Because there is no execute code module.



Look at the code, there is only 1 module ("item) even in there:
https://github.com/CntoDev/compositions/blob/master/reference-adaptations/TFN%2520Jungle/composition.sqe

Compared to an older version that has 2 "items" in there:
https://github.com/CntoDev/compositions/blob/d6d729848b99bc00db553f701d92ee5304e8ec68/reference-adaptations/TFN%2520Desert/composition.sqe

What I imagine happened is whoever updated the modules didn't place down an inhibitor module first, and unfortunately there is no indication that you've missed anything as execute code modules immediately delete themselves, so they made their changes and then saved the single module.

**Comment by JamesTheClarke** [comment]
Interesting. I'm kinda confused about the edited modules tho. I haven't updated them afaik ever since I changed them last in October 30.08.2020 (that's the versions I'm using which is working).

Gonna have to check the commits to see when they were changed and how.

**Comment by Seb105** [comment]
Highway fixed the vehicle camo last month which is part of the same composition, that is when they were broken. Like I said the mistake is easily made if you don't know about self-deleting code modules.

Nonetheless, it proves that they weren't checked at all before merging.

**Comment by JamesTheClarke** [comment]
Yeah, when I review I usually rely on the changelog provided in the PR since diff files in compositions tend to be ginormous. The changelog only mentioned the issue referencing vehicle camos. I tested that module and since it worked for me I gave a greenlight.

I think PR changelogs should mention if a PR addresses more than the original issue reports otherwise things can get overlooked very easily. For example in my latest PR I mention every other change that isn't directly related to the linked issues so reviewers know what to look for during spot testing: https://github.com/CntoDev/compositions/pull/146

**Comment by freghar** [comment]
For the record, I could add a checkbox to `Execute Code (Eden)` modules that would prevent deletion, however you then **have to** make sure the code is safe against repeated executions happening at any possible time (ie. no units placed, some TFN units placed, all TFN units present, TFN units with already modified loadout, mission makers making changes to loadouts via Arsenal, etc., etc.).

This is because the code will be executed on every module placement, copy/paste, pressing OK, mission load, maybe even module move. That's the reason why it self-deletes itself by default, to really execute just once and ie. not overwrite changes made by the MM (in scenario settings, on units via Arsenal, etc.).

**Comment by Seb105** [comment]
Well, this PR didn't _change_ TFN unit camo at all as it wasn't broken/in the scope of the PR, it wouldn't be mentioned in the PR for that reason.

The problem is that the entire module was removed from the composition, obviously completely by accident as it's a very easy mistake to make. One which can't be safeguarded against practically for the reasons Freghar mentioned.

**Comment by JamesTheClarke** [comment]
I've reverted the TFN infantry camo modules back to August 2020 state and committed it to PR #146

**Comment by Seb105** [comment]
Just fyi in case there is some miscommunication: The camo and vehicle modules are 2 separate things which use entirely different game logic to do what they need to do. Fixing one doesn't break the other.

**Comment by milivojm** [comment]
Honestly, can't recall the uniform part but I did check the vehicle and solved it.

Anyway, how about we solve this through a script instead of removable module?
