### ISSUE TITLE
MMG gunner spawns naked when jip

### ISSUE THREAD

**Issue by Shiny-CNTO** [CntoDev/compositions#215]

**Comment by Seb105** [comment]
This will be an issue with the restore arsenal loadout code, mission, or server, not the compositions.

Is this reproducible?

**Comment by Shiny-CNTO** [comment]
It happened 4 times tonight. We tried completely closing arma, disconnecting and connecting again. In the end we could not fix this without the arsenal.

**Comment by Seb105** [comment]
Sometimes the mission bugs out, I mean is it reproducible across missions or sessions?

Naked people is a long standing issue with Arma, very likely not to be related to the composition itself

**Comment by freghar** [comment]
+1, likely not caused by the composition.

My guess would be `cba_network_loadoutValidation`, so I would try disabling that, along with increasing headless transfer delay (a setting in the editor module) from 1 second to 10 seconds, to avoid AI being naked too often (something `cba_network_loadoutValidation` was meant to address, but does it only somewhat well, Arma being Arma).

**Comment by Shiny-CNTO** [comment]
Would be good to check again this Friday. Can we move this issue to the 
CBA repo ?

**Comment by Seb105** [comment]
They're aware of the issue and make attempts at fixes every so often. No telling if it was even CBA here

**Comment by JamesTheClarke** [comment]
We've played a few times since with MMG and I didn't notice this issue come up again. Closing it for now, feel free to reopen the issue in the [CBA Settings repository](https://github.com/CntoDev/cba-settings-lock) if it pops up again.
