### ISSUE TITLE
Suggestion: Give Engineers more ammo

### ISSUE THREAD

**Issue by Seb105** [CntoDev/compositions#83]
Engineers only have 4 mags, they have loads of spare space in their backpacks and vests too. 
Rifleman first is a general principle and they cannot function as riflemen with this issue.

**Comment by Shiny-CNTO** [comment]
Agree that we should add more. Maybe double it.

**Comment by JamesTheClarke** [comment]
The ENG mags were reduced a long time ago mainly to avoid having ENG seeking combat and becoming a frontline element. Though it wasn't implemented across all three factions for some reason (some had six mags, other four etc.), I assume due to oversight.

Personally, I think 5x30 rounds as the current loadout, is sufficient for their main tasking, when people drop they can always loot more mags to help out if the situation requires it. It's a similar design philosophy to having low mag counts for DMT to lock them into a certain playstyle in alignment with their role.

**Comment by Seb105** [comment]
I disagree with that philosophy, a group needs to be capable of effectively operating as a its own and combat is a part of that. Additionally, Eng avoiding combat is antithetical to our playercounts and playstyle. 

I agree with the reasons a bit more for DMT, if we want a consistent approach I'm not against upping their ammo count. To my mind the reason ammocounts were always limited were that they are inherently overpowered with their weapon, which isn't the case for an Engineer element so a different situation.

Right now, all this is doing is making engineers go "wtf" upon spawning and immediately grabbing 10 mags upon the first opporturnity. I know this I have both been the one going "wtf" and I've witnessed people going "wtf"

**Comment by JamesTheClarke** [comment]
Power balance in my view is also a reason why I think a limitation factor should remain in place. Like I said, ENG having less ammo is not new, all I did was make sure that they have the same amount of mags across the three factions, which was the median value of 5 mags in total. I think there can be a case made to up that to a total of 6 or maybe even 7 but I don't think they should gain the same amount ammo as regular platoon riflemen (10) because of the additional power ENG brings to the table.

Each ENG member can:
- Dig a variety of trenches that are extremely effective in fighting against AI
- Repair any captured enemy vehicle back to an operational level and use it against them
- cut through light defenses to create new entries
- have the best body armor both against explosives and bullets

Having less initial ammo is a fairly small drawback in comparison in my view which they can mitigate over time by looting friendly bodies or sharing ammo with friends. Otherwise, ENG members would be just a straight upgrade in almost every way compared to regular platoon members.

**Comment by Seb105** [comment]
7 is fine to me, it's a reasonably practical amount of ammo to have and it makes sense they carry less as they've got other tasks than combat, my argument is that they are straight up _ineffective_ as it stands now.

**Comment by JamesTheClarke** [comment]
As just discussed via TS with Seb it's going to be 6 regular mags and 1 tracer mag per ENG.

ENG leader gets 5 regular mags and 2 tracer mags.

**Comment by Seb105** [comment]
Done for TFN and PMC faction in this branch: https://github.com/CntoDev/compositions/tree/Standard-Factions-1.14.2

**Comment by JamesTheClarke** [comment]
Implemented for [Russian Army draft v.1.14.2](/CntoDev/compositions/tree/Russian-Standard-Faction-Update-v1.14.2)

**Comment by JamesTheClarke** [comment]
Implemented for [US Army v.1.14.2](/CntoDev/compositions/tree/US-Army-Standard-Faction-Update-v1.14.2)
