### ISSUE TITLE
Engineer Team Leader Helmet and Vest change

### ISSUE THREAD

**Issue by CNTODachi** [CntoDev/compositions#9]
The Engineer Team Leader is wearing the wrong type of Vest and Helmet which all leaders should be wearing.

I will update asap.

**Comment by freghar** [comment]
This was on purpose, to have him be identical to the rest of the engineering team. It seemed better at the time to have the entire team look similar and have similar (same if possible) loadout, so that any items one person picks up can be picked up by another person, no load calculation needed.

This is also why all engineering members had all radios (not just the leader).

Additionally, the "team leader" for engineers was meant to be mostly a formality; the use case for engineers was to be intentionally split up most of the time, each doing a separate task possibly miles away from the rest of the team (attached to a squad, etc.).

This is also why they have (had?) a secondary long-range, to coordinate between each other.

As such, it didn't make sense making the team leader look special as the engineering team was really a very loose "team".

**Comment by TRyujin** [comment]
Just like in other supporting elements, I think engineer team should also have a leader with appropriate equipment. Playing previously as engineer we naturally followed the guy in "first" slot. There is no need for all members to have all radios.

**Comment by CNTODachi** [comment]
@milivojm ENGR Lead has been updated to now have correct Helmet and Vest in line with all other leaders.

Ready for Review and Merge e34b75c
