### ISSUE TITLE
TFN Insignia Disappear Upon Respawn

### ISSUE THREAD

**Issue by JamesTheClarke** [CntoDev/compositions#98]
This is something that I've noticed a while ago but always forgot to create an issue for:

When controlled by a player the TFN unit respawning will lose the CNTO Owl insignia for some reason. Might need a create a script that reads the insignia after death.

**Comment by Seb105** [comment]
Keep unit insignia on respawn is an Arma-additions feature. Perhaps this will be fixed when we update, or is set incorrectly now.

**Comment by JamesTheClarke** [comment]
Good stuff. Since you're doing the AA-update testing I'll assign you to this issue.

**Comment by JamesTheClarke** [comment]
Update to this bug: it was "fixed" by A3AA v3.0 but introduced a new bug instead.

Before the predesignated composition CNTO faction insignia patch would disappear upon death. Now insignia respawn after death but the predesignated CNTO faction insignia patch is overwritten by whatever local insignia the player has saved in his/her profile which results in for example Highway and Spartak spawning with their Croatian flag patch instead of the CNTO faction patch.

**Comment by freghar** [comment]
No clue what is "v3.0", but insignia respawn was broken until very recently (https://github.com/freghar/arma-additions/commit/e1f871198be52ab1e44acdfed8c11ef464dd0b0f, 4 days ago) - I tested it when I implemented it, but BI must have broken it since.

I also tested that a mission-forced insignia will overwrite any player-defined one, even if the CBA setting to allow a player insignia is enabled. I tested that the insignia is empty if the mission define none and the player insignia CBA setting is off. This also happened very recently during a rewrite of the logic, https://github.com/freghar/arma-additions/commit/f5dfa03b988a833948bc0dd4323f9f1586954f00

**Comment by JamesTheClarke** [comment]
Yeah, very possible that it's actually a BI bug that coincided timing-wise with us updating A3AA. v3.0 is roughly your repo between May and July, shortly before you tackled the lighting changes (fires, flash lights etc.) for night missions.

**Comment by JamesTheClarke** [comment]
Closing this issue as it can't be fixed via a composition update.
